name: Apprenticeship App Unit Tests

on:
  push:
    branches: ["main"]



jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Build Docker Image
        run: docker build --tag liatrio .
      - name: Run Tests
        uses: liatrio/github-actions/apprentice-action@master 

       