name: Apprenticeship App Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Build Docker Image
        run: docker build --tag liatrio:$(date +%s) .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: liatrio/github-actions/apprentice-action@master
      - name: Run Tests
        run: docker run -p 80:80 -it liatrio