name: Apprenticeship App Unit Tests

on:
  push:
    branches: ["main"]



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Build Docker Image
        run: docker build --tag liatrio .
      
  run-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker Image
        run: docker run -dp 80:80 liatrio
      - name: Run Tests
        uses: liatrio/github-actions/apprentice-action@master