name: Apprenticeship App Unit Tests
description: Tests the behaviour of the developped web app
runs:
  using: docker
  image: docker://ghcr.io/liatrio/github-actions/apprentice-action:latest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master