name:  Build/Push Docker Image to Docker Hub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  #
  REGISTRY: docker.io
  IMAGE_NAME: ${{gadhiaeesha/liatrio}}

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
      -uses: liatrio/github-actions/apprentice-action@master
      -name: Build and verify Docker image
      run: docker build --tag liatrio:$(date +%s) liatrio

  push_to_reg:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -name: 


