name:  Build/Push Docker Image to Docker Hub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

#env:
  #
  #REGISTRY: docker.io
  #IMAGE_NAME: ${{gadhiaeesha/liatrio}}

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build --tag liatrio:$(date +%s) .

  #verify:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: liatrio/github-actions/apprentice-action@master
      #- name: Run Tests

  #push_to_reg:
    #name: Push Docker Image to Docker Hub
    #runs-on: ubuntu-latest
    #steps:
      #- name: Check out repo
        #uses: actions/checkout@v3

      #- name: Set up Docker Buildx
        #uses: docker/setup-buildx-action@v2

      #- name: Log in to Docker Hub
        #uses: docker/login-action@v1
        #with: 
          #username: ${{ secrets.gadhiaeesha }}
          #password: ${{ secrets.gadhiaeesha }}

      #- name: Build and push to Docker Hub
        #uses: docker/build-push-action@v2
        #with:
          #context:  .
          #push: true
          #tags: 
      


